// utility functions

function add(a, b) {
  return a + b;
}

function add(a, b) {
  return a + b;
}

function buggyFunc() {
  throw new Error('Crash on purpose'); // Line 42
}
